stages:
  - publish

publish:
  stage: publish
  image: node:22
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - npm ci
    - npm version ${CI_COMMIT_TAG#v} --no-git-tag-version
    - npm run build
    - |
      npm config set '//gitlab.h1m1.space/api/v4/packages/npm/:_authToken' "${CI_JOB_TOKEN}"
    - npm publish
